# Site settings
title: Omnia Salud News
email: news@omniasalud.com
description: > # this means to ignore newlines until "baseurl:"
  Un blog con la última información sobre informática médica.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://news.omniasalud.com" # the base hostname & protocol for your site
# twitter_username: fernandezpablo
# github_username:  fernandezpablo85

# Build settings
markdown: kramdown
